using System.Diagnostics;
using System.Security.Cryptography;
using Microsoft.Data.Sqlite;
using WorkBookmark.Core;
using WorkBookmark.Storage;

var suite = new PolicyStorageSuite();
int baselineResult = suite.Run();
int extendedResult = ExtendedTargetChecks.Run();
int snapshotResult = NotepadSnapshotChecks.Run();
return baselineResult == 0 && extendedResult == 0 && snapshotResult == 0 ? 0 : 1;

internal sealed class PolicyStorageSuite
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "WorkBookmark-tests-" + Guid.NewGuid().ToString("N"));
    private int _passed;
    private int _failed;

    public int Run()
    {
        Directory.CreateDirectory(_root);
        Run("E06/X12 Windows path policy and conservative identity", Paths);
        Run("E07 Document allowlist and executable reveal policy", DocumentPolicy);
        Run("X01/X12 Absolute single Excel cell bounds", ExcelPolicy);
        Run("U05/U06/U07 Duplicate capture preserves note and separates cells", Deduplication);
        Run("U08 Sequence survives clock rollback, notes, resume, and restart", Ordering);
        Run("U10 Delete, undo, and recapture preserve identity and notes", Deletion);
        Run("U13 Full-history search, literal query, and result bounds", Search);
        Run("D01/D02 All mutation failures roll back without false commits", Rollback);
        Run("E09 Relink preserves metadata and rejects collisions/location edits", Relink);
        Run("D03 Corruption and unknown schemas are preserved", Corruption);
        Run("D03 Migration creates consistent backup and rolls back on failure", Migration);
        Run("D01 Concurrent writer serialization keeps unique monotonic sequence", ConcurrentWrites);
        Run("D01/D02 Real SQLite writer lock fails atomically within a bounded wait", DatabaseLock);
        Console.WriteLine($"RESULT: {_passed} passed; {_failed} failed. Policy/SQLite execution only; Windows/Office acceptance remains separate.");
        // This tree was freshly generated by this test process under the OS temp folder.
        Directory.Delete(_root, recursive: true);
        return _failed == 0 ? 0 : 1;
    }

    private void Run(string title, Action test)
    {
        try { test(); _passed++; Console.WriteLine("PASS " + title); }
        catch (Exception ex) { _failed++; Console.WriteLine("FAIL " + title + ": " + ex); }
    }
    private string Db() => Path.Combine(_root, Guid.NewGuid().ToString("N") + ".db");
    private static CapturedTarget FileTarget(string name = "original") => new(TargetKind.File, @"C:\synthetic\" + name + ".txt");
    private static CapturedTarget Cell(string address = "$D$127", string path = @"C:\synthetic\같은이름.xlsx") => new(TargetKind.ExcelCell, path, "확정자", address, true);
    private static void Check(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
    private static void Fails(Action action, ResultCode code = ResultCode.UnsupportedTarget)
    {
        try { action(); }
        catch (BookmarkException ex) when (ex.Code == code) { return; }
        throw new InvalidOperationException("Expected " + code);
    }

    private static void Paths()
    {
        Check(PathPolicy.Normalize(@"c:/한글 공백 & 괄호 (검증)/folder/../file.txt") == @"c:\한글 공백 & 괄호 (검증)\file.txt", "Unicode, symbols, and case must survive");
        Check(PathPolicy.Normalize(@"D:\a\\b\.\") == @"D:\a\b", "Normalize only separators and dot components");
        Check(PathPolicy.Normalize(@"D:\") == @"D:\", "Retain drive root separator");
        Check(PathPolicy.Normalize(@"\\server\share") == @"\\server\share\", "UNC share root is valid");
        Check(PathPolicy.Normalize(@"\\server\share\a\..\") == @"\\server\share\", "Preserve UNC root");
        Check(PathPolicy.Normalize("C:\\é.txt") != PathPolicy.Normalize("C:\\e\u0301.txt"), "Do not normalize Unicode");
        foreach (string bad in new[] { "relative.txt", @"C:relative.txt", @"\root-relative", "https://host/file.xlsx", "javascript:alert(1)", @"\\?\C:\file.txt", @"\\.\C:\file.txt", @"\??\C:\file.txt", @"C:\file.txt:stream", @"C:\a:stream\file", @"C:\file?.txt", @"C:\file*.txt", @"C:\file|name", @"C:\file" + '\0', @"C:\NUL.txt", @"C:\CON .txt", @"C:\COM1", @"C:\LPT¹.txt", @"C:\file.\child", @"C:\trailing ", @"C:\..\escape", @"\\server", @"\\server\\share", @"\\server\share\..\outside", @"\\localhost\pipe\device", @"\\server\MAILSLOT\device" })
            Fails(() => PathPolicy.Normalize(bad));
        Fails(() => PathPolicy.Validate(new CapturedTarget(TargetKind.File, @"C:\")));
    }

    private static void DocumentPolicy()
    {
        foreach (string extension in new[] { "DOC", "docx", "docm", "rtf", "xls", "xlsx", "xlsm", "xlsb", "csv", "ppt", "pptx", "pptm", "pdf", "txt", "md", "hwp", "hwpx", "png", "jpg", "jpeg", "gif", "bmp", "tif", "tiff" })
            Check(PathPolicy.ShouldOpenDocument(@"C:\synthetic\file." + extension), "Allowlisted " + extension);
        foreach (string extension in new[] { "exe", "com", "msi", "bat", "cmd", "ps1", "vbs", "js", "py", "lnk", "url", "hta", "scr", "unknown", "" })
            Check(!PathPolicy.ShouldOpenDocument(@"C:\synthetic\document.pdf" + (extension == "" ? "-noextension" : "." + extension)), "Reveal only " + extension);
        Fails(() => PathPolicy.ShouldOpenDocument(@"C:\document.txt:payload.exe"));
    }

    private static void ExcelPolicy()
    {
        Check(PathPolicy.Validate(Cell("$XFD$1048576")) == Cell("$XFD$1048576"), "Last valid Excel cell");
        foreach (string address in new[] { "A1", "$A1", "A$1", "$A$0", "$A$01", "$XFE$1", "$A$1048577", "$A$1:$B$2", "=$A$1", "$a$1", "$A$1\n", "'Sheet'!$A$1" })
            Fails(() => PathPolicy.Validate(Cell(address)));
        Fails(() => PathPolicy.Validate(Cell() with { SheetName = "invalid/sheet" }));
        Fails(() => PathPolicy.Validate(Cell() with { SheetName = new string('A', 32) }));
        Fails(() => PathPolicy.Validate(Cell() with { HadUnsavedChanges = null }));
        Fails(() => PathPolicy.Validate(Cell(path: @"C:\synthetic\file.csv")));
        Fails(() => PathPolicy.Validate(FileTarget() with { CellAddress = "$A$1" }));
    }

    private void Deduplication()
    {
        var now = DateTimeOffset.Parse("2026-09-18T05:00:00Z");
        using var repo = new SqliteBookmarkRepository(Db(), utcNow: () => now);
        var first = repo.UpsertCapture(Cell()).Bookmark;
        repo.UpdateNote(first.Id, "검토 완료");
        var noted = repo.Get(first.Id)!;
        now = now.AddHours(1);
        var recaptured = repo.UpsertCapture(Cell() with { HadUnsavedChanges = false });
        Check(recaptured.Bookmark.Id == first.Id && recaptured.ExistingNotePreserved, "One identity, previous-note indicator");
        Check(recaptured.Bookmark.Note == noted.Note && recaptured.Bookmark.NoteUpdatedAtUtc == noted.NoteUpdatedAtUtc, "Preserve note and note timestamp");
        Check(recaptured.Bookmark.CreatedAtUtc == first.CreatedAtUtc && recaptured.Bookmark.CapturedAtUtc == now, "Original creation and new capture time");
        repo.UpsertCapture(Cell("$D$128"));
        repo.UpsertCapture(new CapturedTarget(TargetKind.File, Cell().Path));
        repo.UpsertCapture(Cell(path: @"C:\SYNTHETIC\같은이름.xlsx"));
        Check(repo.List().Items.Count == 4, "Cells, file-only, and case variants remain distinct");
        Fails(() => repo.UpdateNote(first.Id, new string('가', 501)), ResultCode.InvalidRequest);
        Fails(() => repo.UpdateNote(first.Id, "line1\nline2"), ResultCode.InvalidRequest);
        Check(repo.Get(first.Id)!.Note == noted.Note, "Rejected note cannot alter captured record");
    }

    private void Ordering()
    {
        string database = Db();
        var now = DateTimeOffset.Parse("2026-09-18T05:00:00Z");
        Guid firstId;
        long finalSequence;
        using (var repo = new SqliteBookmarkRepository(database, utcNow: () => now))
        {
            var first = repo.UpsertCapture(FileTarget("first")).Bookmark;
            firstId = first.Id;
            now = now.AddDays(-1);
            var second = repo.UpsertCapture(FileTarget("second")).Bookmark;
            Check(second.CapturedAtUtc < first.CapturedAtUtc && repo.List().Items[0].Id == second.Id, "Clock rollback does not reorder capture sequence");
            repo.UpdateNote(firstId, "later note");
            repo.RecordResume(firstId, ResultCode.OpenRequested);
            Check(repo.List().Items[0].Id == second.Id, "Resume/note cannot reorder captures");
            finalSequence = repo.UpsertCapture(FileTarget("first")).Bookmark.CaptureSequence;
        }
        using var reopened = new SqliteBookmarkRepository(database);
        Check(reopened.Get(firstId)!.Note == "later note", "Persistent note after restart");
        Check(reopened.UpsertCapture(FileTarget("third")).Bookmark.CaptureSequence > finalSequence, "Sequence persists after restart");
    }

    private void Deletion()
    {
        string fixture = Path.Combine(_root, "untouched.txt");
        System.IO.File.WriteAllText(fixture, "synthetic original");
        using var repo = new SqliteBookmarkRepository(Db());
        var target = new CapturedTarget(TargetKind.File, fixture);
        var first = repo.UpsertCapture(target).Bookmark;
        repo.UpdateNote(first.Id, "keep me");
        repo.SoftDelete(first.Id);
        Check(repo.List().Items.Count == 0 && repo.Get(first.Id)!.DeletedAtUtc != null, "Soft deletion hides record");
        repo.Restore(first.Id);
        Check(repo.Get(first.Id)!.CaptureSequence == first.CaptureSequence && repo.Get(first.Id)!.Note == "keep me", "Undo preserves sequence and note");
        repo.SoftDelete(first.Id);
        var restored = repo.UpsertCapture(target);
        Check(restored.RestoredDeleted && restored.ExistingNotePreserved && restored.Bookmark.Id == first.Id, "Recapture restores deleted identity and note");
        Check(System.IO.File.ReadAllText(fixture) == "synthetic original", "Original file untouched");
    }

    private void Search()
    {
        using var repo = new SqliteBookmarkRepository(Db());
        for (int i = 0; i < 1000; i++) repo.UpsertCapture(FileTarget($"fixture-{i:D4}"));
        var old = repo.UpsertCapture(new CapturedTarget(TargetKind.File, @"D:\다른 폴더\oldest.txt")).Bookmark;
        repo.UpdateNote(old.Id, "100%_literal 한글 메모");
        for (int i = 0; i < 25; i++) repo.UpsertCapture(FileTarget("recent-" + i));
        var watch = Stopwatch.StartNew();
        var recent = repo.List();
        watch.Stop();
        Check(recent.Items.Count == 20 && recent.Items.All(b => b.Id != old.Id), "Recent 20 bound");
        Check(repo.List("한글 메모").Items.Single().Id == old.Id, "Search reads beyond recent 20 and searches notes");
        Check(repo.List("%").Items.Single().Id == old.Id, "Percent is literal, not LIKE wildcard");
        Check(repo.List("fixture-").Items.Count == 100 && repo.List("fixture-").HasMore, "Search 100 bound and more indicator");
        Check(repo.List("다른 폴더").Items.Single().Id == old.Id, "Search path");
        repo.SoftDelete(old.Id);
        Check(repo.List("한글 메모").Items.Count == 0, "Search excludes deleted records");
        Console.WriteLine($"  Synthetic 1,026-record repository recent query: {watch.Elapsed.TotalMilliseconds:F2} ms (not UI p95).");
    }

    private void Rollback()
    {
        string? fail = null;
        using var repo = new SqliteBookmarkRepository(Db(), op => { if (op == fail) throw new IOException("Injected before commit"); });
        var first = repo.UpsertCapture(FileTarget()).Bookmark;
        repo.UpdateNote(first.Id, "committed");
        var baseline = repo.Get(first.Id)!;
        foreach (var item in new (string Op, Action Action)[] {
            ("capture", () => repo.UpsertCapture(FileTarget())),
            ("note", () => repo.UpdateNote(first.Id,"uncommitted")),
            ("delete", () => repo.SoftDelete(first.Id)),
            ("resume", () => repo.RecordResume(first.Id,ResultCode.OpenRequested)),
            ("relink", () => repo.Relink(first.Id,FileTarget("moved"))) })
        {
            fail = item.Op;
            Fails(item.Action, ResultCode.PersistenceFailed);
            Check(repo.Get(first.Id) == baseline, item.Op + " must leave full original record unchanged");
        }
        fail = "capture";
        Fails(() => repo.UpsertCapture(FileTarget("must-not-exist")), ResultCode.PersistenceFailed);
        Check(repo.List().Items.Count == 1, "Failed create has no ghost row");
        fail = null;
        Check(repo.UpsertCapture(FileTarget("next")).Bookmark.CaptureSequence == baseline.CaptureSequence + 1, "Rolled-back captures do not consume sequence");
        repo.SoftDelete(first.Id);
        fail = "restore";
        Fails(() => repo.Restore(first.Id), ResultCode.PersistenceFailed);
        Check(repo.Get(first.Id)!.DeletedAtUtc != null, "Failed restore stays deleted");
    }

    private void Relink()
    {
        using var repo = new SqliteBookmarkRepository(Db());
        var first = repo.UpsertCapture(Cell()).Bookmark;
        repo.UpdateNote(first.Id, "path-only change");
        var old = repo.Get(first.Id)!;
        var other = Cell(path: @"D:\synthetic\same.xlsx");
        repo.UpsertCapture(other);
        Fails(() => repo.Relink(first.Id, other), ResultCode.DuplicateTarget);
        Check(repo.Get(first.Id) == old, "Duplicate collision preserves original");
        Fails(() => repo.Relink(first.Id, Cell("$A$1", @"D:\synthetic\new.xlsx")), ResultCode.InvalidRequest);
        repo.Relink(first.Id, Cell(path: @"D:\synthetic\new.xlsx") with { HadUnsavedChanges = false });
        var changed = repo.Get(first.Id)!;
        Check(changed.Target.Path == @"D:\synthetic\new.xlsx" && changed.Target.HadUnsavedChanges == old.Target.HadUnsavedChanges, "Only path changed; capture state remains historical");
        Check(changed.Note == old.Note && changed.CaptureSequence == old.CaptureSequence && changed.CapturedAtUtc == old.CapturedAtUtc && changed.NoteUpdatedAtUtc == old.NoteUpdatedAtUtc, "Relink does not change captured history");
    }

    private void Corruption()
    {
        string corrupt = Db();
        byte[] bytes = [1, 9, 7, 2, 8, 3, 6, 4, 5];
        System.IO.File.WriteAllBytes(corrupt, bytes);
        Fails(() => { using var _ = new SqliteBookmarkRepository(corrupt); }, ResultCode.PersistenceFailed);
        Check(System.IO.File.ReadAllBytes(corrupt).SequenceEqual(bytes), "Corrupt bytes preserved exactly");
        foreach (string schema in new[] { "CREATE TABLE foreign_data(value TEXT); INSERT INTO foreign_data VALUES('keep');", "PRAGMA user_version=99;" })
        {
            string database = Db();
            using (var db = OpenSqlite(database)) { using var command = db.CreateCommand(); command.CommandText = schema; command.ExecuteNonQuery(); }
            byte[] hash = SHA256.HashData(System.IO.File.ReadAllBytes(database));
            Fails(() => { using var _ = new SqliteBookmarkRepository(database); }, ResultCode.PersistenceFailed);
            Check(SHA256.HashData(System.IO.File.ReadAllBytes(database)).SequenceEqual(hash), "Unknown/future schema preserved exactly");
        }
    }

    private void Migration()
    {
        string database = Db();
        using (var db = OpenSqlite(database))
        {
            using var command = db.CreateCommand();
            command.CommandText = "CREATE TABLE preparation(value TEXT); DROP TABLE preparation; PRAGMA user_version=0;";
            command.ExecuteNonQuery();
        }
        Fails(() => { using var _ = new SqliteBookmarkRepository(database, op => { if (op == "migration") throw new IOException("Injected migration failure"); }); }, ResultCode.PersistenceFailed);
        string backup = Directory.GetFiles(_root, Path.GetFileName(database) + ".pre-migration-*.bak").Single();
        foreach (string path in new[] { database, backup })
        {
            using var db = OpenSqlite(path);
            using var check = db.CreateCommand();
            check.CommandText = "PRAGMA quick_check";
            Check((string?)check.ExecuteScalar() == "ok", "Original and backup internally consistent");
            check.CommandText = "PRAGMA user_version";
            Check(Convert.ToInt32(check.ExecuteScalar()) == 0, "Migration version rolled back");
            check.CommandText = "SELECT count(*) FROM sqlite_master WHERE name='bookmarks'";
            Check(Convert.ToInt32(check.ExecuteScalar()) == 0, "Uncommitted schema absent");
        }
        using var migrated = new SqliteBookmarkRepository(database);
        Check(migrated.UpsertCapture(FileTarget()).Bookmark.CaptureSequence == 1, "Valid retry after explicit failure works");
    }

    private void ConcurrentWrites()
    {
        using var repo = new SqliteBookmarkRepository(Db());
        var tasks = Enumerable.Range(0, 20).Select(i => Task.Run(() => repo.UpsertCapture(FileTarget("concurrent-" + i)).Bookmark)).ToArray();
        Task.WaitAll(tasks);
        Check(tasks.Select(t => t.Result.CaptureSequence).Order().SequenceEqual(Enumerable.Range(1, 20).Select(i => (long)i)), "Exactly one monotonic sequence per concurrent commit");
    }

    private void DatabaseLock()
    {
        string database = Db();
        using var repo = new SqliteBookmarkRepository(database);
        var first = repo.UpsertCapture(FileTarget()).Bookmark;
        using var external = OpenSqlite(database);
        using (var transaction = external.BeginTransaction())
        {
            var elapsed = Stopwatch.StartNew();
            Fails(() => repo.UpsertCapture(FileTarget("blocked")), ResultCode.PersistenceFailed);
            elapsed.Stop();
            Check(elapsed.Elapsed < TimeSpan.FromSeconds(15), "Busy database must not block without a bound");
            Check(repo.Get(first.Id) == first, "Real lock failure preserves original");
            Console.WriteLine($"  Real SQLite writer lock rejected after {elapsed.Elapsed.TotalSeconds:F2} s.");
            transaction.Rollback();
        }
        Check(repo.List().Items.Count == 1, "Locked capture has no uncommitted row");
        Check(repo.UpsertCapture(FileTarget("after-lock")).Bookmark.CaptureSequence == 2, "Sequence and writes recover after lock release");
    }

    private static SqliteConnection OpenSqlite(string path)
    {
        var db = new SqliteConnection(new SqliteConnectionStringBuilder { DataSource = path, Pooling = false }.ToString());
        db.Open();
        return db;
    }
}
