<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>WorkBookmark</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/WorkBookmark.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets/WorkBookmark.ico" LogicalName="WorkBookmark.Assets.WorkBookmark.ico" />
    <EmbeddedResource Include="Assets/WorkBookmark.Tray.ico" LogicalName="WorkBookmark.Assets.WorkBookmark.Tray.ico" />
    <ProjectReference Include="../WorkBookmark.Core/WorkBookmark.Core.csproj" />
    <ProjectReference Include="../WorkBookmark.Windows/WorkBookmark.Windows.csproj" />
    <ProjectReference Include="../WorkBookmark.Storage/WorkBookmark.Storage.csproj" />
  </ItemGroup>
</Project>
